export const MOVIES_FETCH_FAILED = 'MOVIES_FETCH_FAILED';
export const MOVIES_FETCH_SUCCEEDED = 'MOVIES_FETCH_SUCCEEDED';
export const FETCH_REQUESTED = 'FETCH_REQUESTED';
export const START_PLAYING = 'START_PLAYING';
export const LOGIN_USER = 'LOGIN_USER';
